# DESAFIO 070
# CRIE UM PROGRAMA QUE LEIA O NOME E O PREÇO DE VÁRIOS PRODUTOS. 
# O PROGRAMA DEVERÁ PERGUNTAR SE O USUÁRIO VAI CONTINUAR OU NÃO. 
# NO FINAL, MOSTRE:
# A) QUAL É O TOTAL GASTO NA COMPRA.
# B) QUANTOS PRODUTOS CUSTAM MAIS DE R$1000.
# C) QUAL É O NOME DO PRODUTO MAIS BARATO.

print('\n\033[34m====== DESAFIO 70 ======\n\033[m')