# DESAFIO 062
# MELHORE O DESAFIO 61, PERGUNTANDO PARA O USUÁRIO 
# SE ELE QUER MOSTRAR MAIS ALGUNS TERMOS. 
# O PROGRAMA ENCERRARÁ QUANDO ELE DISSER QUE QUER MOSTRAR 0 TERMOS.

print('\n\033[34m====== DESAFIO 62 ======\n\033[m')
