# DESAFIO 064
# CRIE UM PROGRAMA QUE LEIA VÁRIOS NÚMEROS INTEIROS PELO TECLADO. 
# O PROGRAMA SÓ VAI PARAR QUANDO O USUÁRIO DIGITAR O VALOR 999, QUE É A CONDIÇÃO DE PARADA. 
# NO FINAL, MOSTRE QUANTOS NÚMEROS FORAM DIGITADOS 
# E QUAL FOI A SOMA ENTRE ELES (DESCONSIDERANDO O FLAG).

print('\n\033[34m====== DESAFIO 64 ======\n\033[m')
