# DESAFIO 065
# CRIE UM PROGRAMA QUE LEIA VÁRIOS NÚMEROS INTEIROS PELO TECLADO. 
# NO FINAL DA EXECUÇÃO, MOSTRE A MÉDIA ENTRE TODOS OS VALORES 
# E QUAL FOI O MAIOR E O MENOR VALORES LIDOS. 
# O PROGRAMA DEVE PERGUNTAR AO USUÁRIO SE ELE QUER OU NÃO CONTINUAR A DIGITAR VALORES.

print('\n\033[34m====== DESAFIO 65 ======\n\033[m')
