# DESAFIO 063
# ESCREVA UM PROGRAMA QUE LEIA UM NÚMERO N INTEIRO QUALQUER 
# E MOSTRE NA TELA OS N PRIMEIROS ELEMENTOS DE UMA SEQUÊNCIA DE FIBONACCI. 
# EXEMPLO: 0 – 1 – 1 – 2 – 3 – 5 – 8

print('\n\033[34m====== DESAFIO 63 ======\n\033[m')
