# DESAFIO 088
# FAÇA UM PROGRAMA QUE AJUDE UM JOGADOR DA MEGA SENA A CRIAR PALPITES.
# O PROGRAMA VAI PERGUNTAR QUANTOS JOGOS SERÃO GERADOS 
# E VAI SORTEAR 6 NÚMEROS ENTRE 1 E 60 PARA CADA JOGO, 
# CADASTRANDO TUDO EM UMA LISTA COMPOSTA.

print('\n\033[34m====== DESAFIO 88 ======\n\033[m')
