# DESAFIO 087
# APRIMORE O DESAFIO ANTERIOR, MOSTRANDO NO FINAL:                                                    
# A) A SOMA DE TODOS OS VALORES PARES DIGITADOS.
# B) A SOMA DOS VALORES DA TERCEIRA COLUNA.
# C) O MAIOR VALOR DA SEGUNDA LINHA.

print('\n\033[34m====== DESAFIO 87 ======\n\033[m')
