# DESAFIO 089
# CRIE UM PROGRAMA QUE LEIA NOME E DUAS NOTAS DE VÁRIOS ALUNOS E GUARDE TUDO EM UMA LISTA COMPOSTA. 
# NO FINAL, MOSTRE UM BOLETIM CONTENDO A MÉDIA DE CADA UM 
# E PERMITA QUE O USUÁRIO POSSA MOSTRAR AS NOTAS DE CADA ALUNO INDIVIDUALMENTE.

print('\n\033[34m====== DESAFIO 89 ======\n\033[m')
