# DESAFIO 086
# CRIE UM PROGRAMA QUE DECLARE UMA MATRIZ DE DIMENSÃO 3×3 
# E PREENCHA COM VALORES LIDOS PELO TECLADO. 
# NO FINAL, MOSTRE A MATRIZ NA TELA, COM A FORMATAÇÃO CORRETA.

print('\n\033[34m====== DESAFIO 86 ======\n\033[m')
